### PR TITLE
Added Remove Duplicate Button (issues #18)

### LINKED ISSUE #18: Add button/block to remove duplicate rows
Block UI should show how many duplicated where removed

### PR DESCRIPTION
**Pull request by Nitinyadav237**
**### Description**
I have added a "Remove Duplicate" button to the Block UI, which facilitates the removal of duplicate rows based on the selected column.

**### Issue**
This PR resolves the issue #18, where the requirement was to implement functionality to remove duplicate rows in the Block UI. The issue was opened by @ramonverse last week.

**### Changes Made**
- Introduced a new button labeled "Remove Duplicate" to the Block UI interface.
- Implemented logic to identify and remove duplicate rows based on the selected column.
- Enhanced the user experience by providing feedback on the number of duplicate rows removed.

**### How It Works**
When the "Remove Duplicate" button is clicked, the system identifies duplicate rows within the selected column and removes them from the dataset. The Block UI is updated to reflect the changes, showing the user how many duplicate rows were successfully removed.

fixes #18 

https://github.com/pretzelai/pretzelai/assets/113238477/20d282d0-3491-4400-beba-23050e0191bf

### CODE REVIEW

**Comment by prasoon2211** [comment]
Thanks for the PR Nitin! It looks good from a fist look - will take a look tomorrow for merging.

**Comment by ramonverse** [comment]
Hi @Nitinyadav237 , thank you for putting this together.
When processing CSVs it is very common to have duplicate rows, where every single field is the same (see attached picture).
That is the main functionality I was aiming for in #18 . I'd suggest you modify your block so the dropdown has a default option called "Full row" that gets executed automatically when you add the "Remove Duplicates" row.
Also, when I change the selected column in the dropdown it should be reactive and remove the duplicates.
I have attached an example file where you can see full duplicates and test your code.
image
[editors_data_with_duplicates.csv](https://github.com/pretzelai/pretzelai/files/14733425/editors_data_with_duplicates.csv)

Let me know if you have any question!

**Comment by Nitinyadav237** [comment]
https://github.com/pretzelai/pretzelai/assets/113238477/991e5dfe-1f11-4985-88a5-aebe887cfe75

is it okay?

**Comment by ramonverse** [comment]
Hi @Nitinyadav237 , nope. It should remove the duplicates from the csv example I posted, not just be a placeholder. The PRQL query it should call with "Full row" is:
`group {\`${allColumns.join("`,`")}\`} (take 1)`

**Comment by Nitinyadav237** [comment]
now  is it okay ?

https://github.com/pretzelai/pretzelai/assets/113238477/16bb988e-c138-48c0-9c0d-9facdb463810

**Comment by ramonverse** [comment]
Hi @Nitinyadav237 ,
I am refactoring the code and writing contributing instructions to make it easier to open PRs. There are many cases to take into account with Pretzel, one being reactivity. With your code if I have a previous block (e.g. a filter), your remove duplicates will not update when the previous block changes.
From here
image

to here:
image

Also, the 500ms timeout in your code shouldn't be there. Pretzel should behave as fast as possible :)

**Comment by Nitinyadav237** [comment]
https://github.com/pretzelai/pretzelai/assets/113238477/ed46fb5c-9e8e-4f5a-a6ab-d4b9ac4bf73c

**Comment by ramonverse** [comment]
Well done @Nitinyadav237 , I think we can merge for now thanks!

**Pull request merged**
