### PR TITLE
42-SQL/PRQL-syntax-highlighting-issued-solved

### PR DESCRIPTION
**Pull request by Nitinyadav237**
@ramonverse 
#42 SQL/PRQL-syntax-highlighting-issued-solved

https://github.com/pretzelai/pretzelai/assets/113238477/9767f881-ffc5-4ca4-9fc0-bf727dc39ede

### CODE REVIEW

**Comment by Nitinyadav237** [comment]
@ramonverse  If you'd like to adjust the color scheme, please specify the desired changes. 

 { token: "keyword.sql", foreground: "#48db40", fontStyle: "italic bold" },
    { token: "white.sql", foreground: "#c0d218", fontStyle: "italic bold" },
    { token: "operator.sql", foreground: "#48db40", fontStyle: "italic bold" },
    { token: "comment.sql", foreground: "#4673e6", fontStyle: "italic bold" },
    { token: "identifier.sql", foreground: "#db4055", fontStyle: "italic bold" },

    { token: "keyword.prql", foreground: "#e3c91e", fontStyle: "italic bold" },
    { token: "white.prql", foreground: "#21f140", fontStyle: "italic bold" },
    { token: "operator.prql", foreground: "#d8550f", fontStyle: "italic bold" },
    { token: "identifier.prql", foreground: "#095c94", fontStyle: "bold italic" },
    { token: "comment.prql", foreground: "#6e0dc9", fontStyle: "bold italic" },

**Comment by Nitinyadav237** [comment]
I have solved the #42 SQL / PRQL syntax highlighting 
**Description:**

   1.Created editor.tsx, which contains a custom theme for the editor and PRQL language configuration.
   2.In userquery.tsx, added loader.init() to load the custom theme and set PRQL language configuration. 
   3.Added separate states sqlUserInput and prqlUserInput to preserve user-typed values in the editor.
   
   



https://github.com/pretzelai/pretzelai/assets/113238477/6b4442b4-35a2-4b4e-b6f9-d730bdbe569b

**Comment by ramonverse** [comment]
@Nitinyadav237  can we remove the italic? also the font looks way bigger than the rest of the app and there is unnecessary margin between the box and the line numbers. Can you fix that? thank you!

**Comment by Nitinyadav237** [comment]
@ramonverse :
            1. Italics removed.
            2.Font size reduced to 14px.
            3.Eliminated unnecessary margin between the box and the line numbers.
              
              
image



How do you feel about the color?

image

**Pull request merged**
