### PR TITLE
#42  issue: SQL/PRQL Syntax Highlighting

### PR DESCRIPTION
**Pull request by samarsharma2030**
Hello
This PR resolves the issue #42  (SQL / PRQL syntax highlighting). Please check the screen recording for a quick review.

https://github.com/pretzelai/pretzelai/assets/142157401/f7109d8e-ff04-43d9-8537-1798c14ef1c4

Thanks for your time.

### CODE REVIEW

**Review by ramonverse — CHANGES_REQUESTED** [review]
bring the error back

**Comment by avycado13** [comment]
you could add `{isPrqlError && (
      <Label className="text-red-300">Invalid PRQL</Label>
    )}
    {isSqlError && (
      <Label className="text-red-300">Invalid SQL</Label>
    )}` in the same div as the code mirror component

**Comment by samarsharma2030** [comment]
@avycado13 Thanks for your suggestion, had to change some styles and structure as well to display a clean error. Please have a look at the committed code. 
thanks!

**Comment by samarsharma2030** [comment]
@ramonverse Thanks for the review and feedback. Sorry for a late response. I've added the error message as requested. Please check the recording for a quick review. 

Uploading SQL-PRQL Error Message.mov…

thanks!

**Comment by samarsharma2030** [comment]
@ramonverse Thanks for the review and feedback. Sorry for a late response. I've added the error message as requested. Please check the recording for a quick review.

https://github.com/pretzelai/pretzelai/assets/142157401/ec7818df-6d79-4c47-9c9f-b249ecd4ac0b

thanks!

**Comment by avycado13** [comment]
@samarsharma2030 does it work for prql?

**Comment by avycado13** [comment]
@samarsharma2030 does it work for prql?

**Comment by ramonverse** [comment]
@samarsharma2030 PRQL support is missing. You can find more info here https://prql-lang.org/book/project/integrations/syntax-highlighting.html
image

**Comment by samarsharma2030** [comment]
Based on the provided information, it seems like the prql-lezer package is in development and not yet published to any package managers. Is it okay to clone prql repository and then integrating with CodeMirror ?

**Comment by ramonverse** [comment]
@samarsharma2030 seems like you will need to probably just copypaste this file somewhere right? https://github.com/PRQL/prql/blob/main/grammars/prql-lezer/src/prql.grammar

**Comment by samarsharma2030** [comment]
Yeah, highlight.js also appears to define syntax highlighting styles for prql. Have to create a separate folder in src called "grammars" and include these two inside that folder. And then import in UserQuery.tsx. Is it like this ?

**Comment by samarsharma2030** [comment]
@ramonverse Yeah, highlight.js file appears to have the styles. It seems we have to create a separate folder "grammars" including both the files and we can go from there. Is it like this ?

**Comment by samarsharma2030** [comment]
@ramonverse Yes, seems like have to create a new folder "grammars" and have this grammar file and highlight.js(styling) file inside  it, then import it in UserQuery.tsx. Is it like this ?

**Comment by ramonverse** [comment]
@samarsharma2030 sounds good

**Comment by samarsharma2030** [comment]
@ramonverse hello, do you know how can we add this exported file as an extension in CodeMirror component? Tried various approaches of assigning the it the type Extension. But always a type error somewhere in the code that says "Type 'null' is not assignable to type 'Extension'." struggling with this

**Comment by ramonverse** [comment]
@samarsharma2030 No I don't. If it's not easy to use just try https://www.npmjs.com/package/@monaco-editor/react we want to migrate to Monaco anyways

**Comment by ramonverse** [comment]
Closed in favor of monaco PR

**Pull request closed without merging**
